server:
  port: 8088
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 30
spring:
  application:
    name: monitorapi
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${POSTGRES_DATA_DB_URL:jdbc:mariadb://mariadb:3306/monitor-db}
    username: ${POSTGRES_DATA_DB_USER:root}
    password: ${POSTGRES_DATA_DB_PASSWORD:admin}
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    locations: classpath:db/migration
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://keycloak:8080/realms/monitor-realm}
          jwk-set-uri: ${JWT_ISSUER_URI:http://keycloak:8080/realms/monitor-realm}/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: ${JWT_ISSUER_URI:http://keycloak:8080/realms/monitor-realm}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:monitor-client}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:W4L0YVZKLyY3aXKocSv4zxHJxvheoekv}
            scope: openid
logging:
  level:
    org:
      springframework:
        security: DEBUG