server:
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 30
spring:
  application:
    name: monitorapi
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${POSTGRES_DATA_DB_URL:jdbc:mariadb://localhost:3307/monitor-db}
    username: ${POSTGRES_DATA_DB_USER:root}
    password: ${POSTGRES_DATA_DB_PASSWORD:admin}
  flyway:
    user: ${POSTGRES_DATA_DB_USER:root}
    password: ${POSTGRES_DATA_DB_PASSWORD:admin}
    url: ${POSTGRES_DATA_DB_URL:jdbc:mariadb://localhost:3307/monitor-db}
    locations: classpath:db/migration
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8088/realms/monitor-realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: ${JWT_ISSUER_URI:http://localhost:8088/realms/monitor-realm}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:monitor-client}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:MvBX45NPMptgSeBG4yF4R6MhLQksroOq}
            scope: openid
